[project]
id = "atlas-local"

[api]
enabled = true
port = 54321

[db]
port = 54322
major_version = 15

[studio]
enabled = true
port = 54323

[auth]
enabled = true
site_url = "http://localhost:8081"
additional_redirect_urls = ["exp://localhost:8081"]

[functions]
verify_jwt = true
