/* Generates the cross-language parity fixture for core/rng/rng.gd.
   Mirrors atlas/packages/engines/src/seed.ts (mulberry32) exactly. */
import { writeFileSync } from "node:fs";

function hashSeed(seed) {
  let h = 1779033703 ^ seed.length;
  for (let i = 0; i < seed.length; i++) {
    h = Math.imul(h ^ seed.charCodeAt(i), 3432918353);
    h = (h << 13) | (h >>> 19);
  }
  return (h >>> 0) || 1;
}
function createRng(seed) {
  let state = hashSeed(seed);
  return () => {
    state = (state + 0x6d2b79f5) | 0;
    let t = Math.imul(state ^ (state >>> 15), 1 | state);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

const seeds = ["fatequest", "zayton:market:1292-04-11", "", "上都", "a"];
const out = { note: "Generated by tools/parity/gen_rng_fixture.mjs from Atlas seed.ts. GDScript Rng must reproduce these bit-for-bit.", cases: [] };
for (const s of seeds) {
  const r = createRng(s);
  out.cases.push({ seed: s, hash: hashSeed(s), first16: Array.from({length:16}, () => r()) });
}
writeFileSync(new URL("rng_fixture.json", import.meta.url), JSON.stringify(out, null, 2));
console.log("wrote rng_fixture.json");
for (const c of out.cases) console.log(`  seed=${JSON.stringify(c.seed).padEnd(28)} hash=${c.hash} first=${c.first16[0].toFixed(12)}`);
