/* 命途塔 Tower of Fates — data (GDD §5)
   Symbols are PIECES: effects are gamified readings of the real meanings.
   up = 正位/本义, rv = 逆位/变爻 (absent rv ⇒ the symbol cannot invert).
   `note` is a real one-line cultural fact, shown when 对照 resonance fires. */
window.FQ = window.FQ || {};

/* effect ops are resolved in tower.js — see FQ.TW.applyOps */
FQ.TOWER_SYMBOLS = [
  /* ============ TAROT (civ: tarot) ============ */
  { id: "sun", civ: "tarot", sym: "☀️", zh: "太阳", en: "The Sun", power: 3, elem: "火",
    upZh: "本层奖励 ×2", upEn: "This floor's rewards ×2", up: [{ op: "reward2x" }],
    rvZh: "下层预兆全部隐藏", rvEn: "Next floor's omens hidden", rv: [{ op: "omenHide" }],
    nZh: "塔罗的太阳常绘双子与向日葵，是十九号牌，象征无须遮掩的成功。",
    nEn: "The Sun, trump XIX, often shows twin children beneath sunflowers — success with nothing to hide." },
  { id: "moon", civ: "tarot", sym: "🌕", zh: "月亮", en: "The Moon", power: 2, elem: "水",
    upZh: "窥见下一层的事件", upEn: "Peek at the next floor", up: [{ op: "peek" }],
    rvZh: "谜面化：考验 +2，酬金 +4", rvEn: "Riddled: demand +2, purse +4", rv: [{ op: "demand", v: 2 }, { op: "coins", v: 4 }],
    nZh: "月亮牌上一犬一狼对月而吠，中央小路通向未知——直觉与迷雾同在。",
    nEn: "On the Moon card a dog and a wolf bay at the sky; the path between them runs into fog — intuition beside illusion." },
  { id: "star", civ: "tarot", sym: "⭐", zh: "星星", en: "The Star", power: 2, elem: "风",
    upZh: "疗愈：体力 +2", upEn: "Healing: +2 vigor", up: [{ op: "hp", v: 2 }],
    rvZh: "微光：体力 +1", rvEn: "Faint light: +1 vigor", rv: [{ op: "hp", v: 1 }],
    nZh: "星星牌绘少女向池中倾水，是大灾变（高塔）之后的第一张牌：希望。",
    nEn: "The Star pours water back into the pool — the first card after the Tower's ruin: hope." },
  { id: "tarot-tower", civ: "tarot", sym: "🗼", zh: "高塔", en: "The Tower", power: 2, elem: "火",
    upZh: "涤荡：清除所有诅咒，受 2 伤", upEn: "Purge all curses, take 2 damage", up: [{ op: "cleanse" }, { op: "hp", v: -2 }],
    rvZh: "余震：随机弃置一枚符号", rvEn: "Aftershock: discard a random symbol", rv: [{ op: "discardRand" }],
    nZh: "高塔源自巴别塔与神罚意象：雷火击顶，王冠坠落——假结构必然崩塌。",
    nEn: "The Tower echoes Babel: lightning strikes the crown from the spire — false structures must fall." },
  { id: "strength", civ: "tarot", sym: "🦁", zh: "力量", en: "Strength", power: 3, elem: "火",
    upZh: "此番力量 +2", upEn: "+2 power this play", up: [{ op: "pow", v: 2 }],
    rvZh: "蛮劲：力量 −1", rvEn: "Brute doubt: −1 power", rv: [{ op: "pow", v: -1 }],
    nZh: "力量牌上少女徒手抚合狮口，以柔克刚——韦特把它换到第八号，与正义对调。",
    nEn: "A maiden closes the lion's jaws bare-handed; Waite swapped Strength to VIII, trading places with Justice." },
  { id: "wheel", civ: "tarot", sym: "🎡", zh: "命运之轮", en: "Wheel of Fortune", power: 1, elem: "土",
    upZh: "时来运转：得 2–10 金", upEn: "Fortune turns: gain 2–10 coin", up: [{ op: "coinsRand", v: [2, 10] }],
    rvZh: "轮下：失 4 金", rvEn: "Under the wheel: lose 4 coin", rv: [{ op: "coins", v: -4 }],
    nZh: "轮上常写 TARO/ROTA 四字回环，转到哪里都读得通——运与命互为回文。",
    nEn: "The wheel bears ROTA/TARO in a ring that reads either way round — fate as a palindrome." },
  { id: "death", civ: "tarot", sym: "🦋", zh: "死神", en: "Death", power: 2, elem: "水",
    upZh: "蜕变：净化一枚诅咒（无则体力 +2）", upEn: "Molt: purify one curse (else +2 vigor)", up: [{ op: "purifyOne" }],
    rvZh: "不舍：体力 −1，星尘 +1", rvEn: "Clinging: −1 vigor, +1 stardust", rv: [{ op: "hp", v: -1 }, { op: "dust", v: 1 }],
    nZh: "死神牌编号十三却极少意指死亡：白玫瑰旗帜下，是章节的更替。",
    nEn: "Trump XIII rarely means dying: beneath its white-rose banner, one chapter yields to the next." },
  { id: "hermit", civ: "tarot", sym: "🏮", zh: "隐者", en: "The Hermit", power: 1, elem: "土",
    upZh: "提灯：预兆连准两层", upEn: "Lantern: true omens for 2 floors", up: [{ op: "omenTrue", v: 2 }],
    rvZh: "离群：此番不触发共鸣", rvEn: "Withdrawn: no resonance this play", rv: [{ op: "noRes" }],
    nZh: "隐者的灯笼里画着六角星（所罗门之印），照见的从来是自己的路。",
    nEn: "Inside the Hermit's lantern burns a six-pointed star; what it lights is always one's own path." },
  { id: "fool", civ: "tarot", sym: "🃏", zh: "愚者", en: "The Fool", power: 1, elem: "风",
    upZh: "轻装：下层手牌 +1", upEn: "Light pack: next floor +1 hand card", up: [{ op: "handUp", v: 1 }],
    rvZh: "失足：失 2 金", rvEn: "A stumble: lose 2 coin", rv: [{ op: "coins", v: -2 }],
    nZh: "愚者编号零，可置于牌序之首或之尾——他是整副塔罗的行路人。",
    nEn: "Numbered 0, the Fool stands at either end of the trumps — the deck's one true traveler." },

  /* ============ I-CHING (civ: iching) ============ */
  { id: "qian", civ: "iching", sym: "䷀", zh: "乾", en: "Qián · Creative", power: 3, elem: "金",
    upZh: "天行健：此番必成", upEn: "Heaven prevails: auto-success", up: [{ op: "autowin" }],
    rvZh: "变爻成姤：下层必逢奇遇", rvEn: "Moving line → Gòu: next floor is a Wonder", rv: [{ op: "nextWonder" }],
    nZh: "乾六爻皆阳。《易》曰「天行健，君子以自强不息」——清华校训取自此。",
    nEn: "Qián is six unbroken lines. 'Heaven moves with vigor; the noble one never rests' — now a university motto." },
  { id: "kun", civ: "iching", sym: "䷁", zh: "坤", en: "Kūn · Receptive", power: 2, elem: "土",
    upZh: "厚德载物：失败不受罚", upEn: "Carries all: no penalty on failure", up: [{ op: "dodge" }],
    rvZh: "变爻成复：体力 +1", rvEn: "Moving line → Fù: +1 vigor", rv: [{ op: "hp", v: 1 }],
    nZh: "坤六爻皆阴，履霜坚冰至；「厚德载物」与乾之「自强」互为表里。",
    nEn: "Kūn is six broken lines: 'treading frost, solid ice will come.' Its devotion mirrors Qián's vigor." },
  { id: "kan", civ: "iching", sym: "䷜", zh: "坎", en: "Kǎn · Abyss", power: 2, elem: "水",
    upZh: "行险：本层得失皆 ×2", upEn: "Into the gorge: gains AND losses ×2", up: [{ op: "stakes", v: "both" }],
    rvZh: "陷溺：失败代价 ×2", rvEn: "Sinking: losses ×2", rv: [{ op: "stakes", v: "loss" }],
    nZh: "坎为重水重险，卦辞却言「有孚维心亨」——险中持诚，反而能通。",
    nEn: "Kǎn doubles the water-gorge, yet its judgment reads: with sincerity, the heart still crosses." },
  { id: "li", civ: "iching", sym: "䷝", zh: "离", en: "Lí · Radiance", power: 2, elem: "火",
    upZh: "明照：本层预兆必真，得 2 金", upEn: "Bright sight: true omens, +2 coin", up: [{ op: "omenTrue", v: 1 }, { op: "coins", v: 2 }],
    rvZh: "日昃：本层预兆隐藏", rvEn: "Sun tilts: omens hidden", rv: [{ op: "omenHide" }],
    nZh: "离为火为目为丽，「日月丽乎天」——附着于光明而行。",
    nEn: "Lí is fire, the eye, and 'clinging': as sun and moon cling to heaven, one clings to clarity." },
  { id: "qian15", civ: "iching", sym: "䷎", zh: "谦", en: "Qiān · Modesty", power: 1, elem: "土",
    upZh: "地中有山：本层风险 −2", upEn: "Mountain within earth: risk −2", up: [{ op: "risk", v: -2 }],
    nZh: "谦是六十四卦中唯一六爻皆吉之卦——谦谦君子，有终。",
    nEn: "Qiān is the only hexagram whose six lines are all auspicious — modesty alone ends well everywhere." },
  { id: "ge", civ: "iching", sym: "䷰", zh: "革", en: "Gé · Molting", power: 2, elem: "火",
    upZh: "鼎新：更换本层事件", upEn: "Renew: redraw this floor's event", up: [{ op: "rerollEvent" }],
    rvZh: "未孚：考验 +1", rvEn: "Untimely: demand +1", rv: [{ op: "demand", v: 1 }],
    nZh: "革取象兽类换毛：「天地革而四时成」，汤武革命亦用此字。",
    nEn: "Gé is the beast shedding its coat in season — the same word later named dynastic revolution." },
  { id: "jin", civ: "iching", sym: "䷢", zh: "晋", en: "Jìn · Progress", power: 2, elem: "火",
    upZh: "昼日三接：得 3 金", upEn: "Thrice received: +3 coin", up: [{ op: "coins", v: 3 }],
    rvZh: "失据：失 1 金", rvEn: "Losing ground: −1 coin", rv: [{ op: "coins", v: -1 }],
    nZh: "晋卦明出地上，卦辞记「康侯用锡马蕃庶，昼日三接」——一日三见君王。",
    nEn: "Jìn is the sun climbing over the earth: a marquis honored three times in a single day." },
  { id: "gen", civ: "iching", sym: "䷳", zh: "艮", en: "Gèn · Stillness", power: 1, elem: "土",
    upZh: "止其所：本层考验 −2", upEn: "Stop where due: demand −2", up: [{ op: "demand", v: -2 }],
    nZh: "艮为山为止：「艮其背，不获其身」——止得其所，则不见咎。",
    nEn: "Gèn is the mountain, stillness itself: stopping at the right place incurs no blame." },

  /* ============ RUNES (civ: runes) ============ */
  { id: "fehu", civ: "runes", sym: "ᚠ", zh: "菲胡", en: "Fehu", power: 1, elem: "土",
    upZh: "牛群：得 6 金", upEn: "Cattle: +6 coin", up: [{ op: "coins", v: 6 }],
    rvZh: "课税：失 4 金", rvEn: "Taxed: −4 coin", rv: [{ op: "coins", v: -4 }],
    nZh: "Fehu 本义是「牲畜」，日耳曼人以牛计财——英语 fee 与之同源。",
    nEn: "Fehu literally means 'cattle', the oldest Germanic wealth — English 'fee' descends from it." },
  { id: "algiz", civ: "runes", sym: "ᛉ", zh: "埃尔哈兹", en: "Algiz", power: 2, elem: "木",
    upZh: "麋角：获得护盾一层", upEn: "Elk-sedge: gain 1 shield", up: [{ op: "shield", v: 1 }],
    rvZh: "倒立：护盾归于对手，考验 +2", rvEn: "Merkstave: the shield turns hostile, demand +2", rv: [{ op: "demand", v: 2 }],
    nZh: "Algiz 形如张开的手掌或麋鹿角，是卢恩中最古老的守护记号。",
    nEn: "Algiz looks like a splayed hand or elk antlers — the oldest ward-sign in the futhark." },
  { id: "isa", civ: "runes", sym: "ᛁ", zh: "伊萨", en: "Isa", power: 1, elem: "水",
    upZh: "冻结：跳过本层事件", upEn: "Freeze: skip this floor's event", up: [{ op: "freeze" }],
    nZh: "Isa 是「冰」：一道竖画，不可倒立——静止本身没有反面。",
    nEn: "Isa is 'ice': a single stave that cannot invert — stillness has no reverse." },
  { id: "sowilo", civ: "runes", sym: "ᛊ", zh: "索维洛", en: "Sowilo", power: 2, elem: "火",
    upZh: "太阳之轮：力量 +1，得 2 金", upEn: "Sun-wheel: +1 power, +2 coin", up: [{ op: "pow", v: 1 }, { op: "coins", v: 2 }],
    nZh: "Sowilo 是太阳，维京船以日位导航；此符无倒位——太阳不会倒挂。",
    nEn: "Sowilo is the sun that steered viking sails; it has no merkstave — the sun cannot hang upside-down." },
  { id: "raidho", civ: "runes", sym: "ᚱ", zh: "莱多", en: "Raidho", power: 2, elem: "风",
    upZh: "车轮：力量 +1，风险 −1", upEn: "The wagon: +1 power, risk −1", up: [{ op: "pow", v: 1 }, { op: "risk", v: -1 }],
    rvZh: "颠簸：力量 −1", rvEn: "Jolted: −1 power", rv: [{ op: "pow", v: -1 }],
    nZh: "Raidho 是「骑行/车轮」，也指节奏与正道——旅程要合它的拍子。",
    nEn: "Raidho is 'riding' — wheel, rhythm and right order; a journey must keep its beat." },
  { id: "perthro", civ: "runes", sym: "ᛈ", zh: "佩斯罗", en: "Perthro", power: 1, elem: "水",
    upZh: "骰盅：得 0–12 金", upEn: "Dice cup: gain 0–12 coin", up: [{ op: "coinsRand", v: [0, 12] }],
    rvZh: "覆盅：失 3 金", rvEn: "Spilled: −3 coin", rv: [{ op: "coins", v: -3 }],
    nZh: "Perthro 意义成谜，多解作骰盅或命签袋——日耳曼人掷签问事见于塔西佗记载。",
    nEn: "Perthro's meaning is lost — likely the dice-cup or lot-bag; Tacitus records Germans casting lots." },
  { id: "uruz", civ: "runes", sym: "ᚢ", zh: "乌鲁兹", en: "Uruz", power: 3, elem: "木",
    upZh: "野牛之力：力量 +2，体力 −1", upEn: "Aurochs: +2 power, −1 vigor", up: [{ op: "pow", v: 2 }, { op: "hp", v: -1 }],
    rvZh: "失蹄：体力 −2", rvEn: "Gored: −2 vigor", rv: [{ op: "hp", v: -2 }],
    nZh: "Uruz 指欧洲野牛 aurochs——猎野牛曾是日耳曼少年的成人礼，此兽已于 1627 年灭绝。",
    nEn: "Uruz names the aurochs, hunted as a Germanic rite of passage; the last aurochs died in 1627." }
];

/* 塔之逆位 curse symbols — dead cards that squat in your library (GDD §5.4) */
FQ.TOWER_CURSES = [
  { id: "c-shadow", sym: "🌑", zh: "阴翳", en: "Gloom",
    dZh: "入手时：本层预兆隐藏", dEn: "When drawn: omens hidden this floor", bite: [{ op: "omenHide" }] },
  { id: "c-chain", sym: "⛓️", zh: "锁蔽", en: "Fetter",
    dZh: "入手时：此番力量 −1", dEn: "When drawn: −1 power this play", bite: [{ op: "pow", v: -1 }] },
  { id: "c-leak", sym: "🕳️", zh: "漏财", en: "Leak",
    dZh: "入手时：失 2 金", dEn: "When drawn: lose 2 coin", bite: [{ op: "coins", v: -2 }] },
  { id: "c-dread", sym: "🐍", zh: "惊惶", en: "Dread",
    dZh: "入手时：本层考验 +1", dEn: "When drawn: demand +1", bite: [{ op: "demand", v: 1 }] }
];

/* ---- archetypes 行者流派 (GDD §5.1) ---- */
FQ.TOWER_ARCH = [
  { id: "tarot", ic: "🔮", color: "var(--c-tarot)",
    zh: "塔罗行者", en: "Tarot Walker", cost: 0,
    deck: ["sun", "moon", "star", "strength", "wheel", "fool"],
    skillZh: "逆转 · 翻转一枚已揭符号的正逆位", skillEn: "Reverse · flip one revealed symbol's orientation",
    skill: "flip" },
  { id: "iching", ic: "☯", color: "var(--c-iching)",
    zh: "易卜师", en: "Diviner of Changes", cost: 15,
    deck: ["qian", "kun", "kan", "li", "qian15", "jin"],
    skillZh: "重卜 · 重抽整手符号", skillEn: "Recast · redraw your whole hand",
    skill: "redraw" },
  { id: "runes", ic: "ᚠ", color: "var(--c-runes)",
    zh: "符文萨满", en: "Rune Shaman", cost: 25,
    deck: ["fehu", "algiz", "isa", "sowilo", "raidho", "perthro"],
    skillZh: "净咒 · 立即净化一枚诅咒", skillEn: "Cleanse · purify one curse at once",
    skill: "purify" }
];

/* ---- codex interop (§5.4): a symbol drops only if met in the main game ---- */
FQ.TOWER_CODEX_LINK = {
  "sun": ["tarot", 19], "moon": ["tarot", 18], "star": ["tarot", 17],
  "tarot-tower": ["tarot", 16], "strength": ["tarot", 8], "wheel": ["tarot", 10],
  "death": ["tarot", 13], "hermit": ["tarot", 9], "fool": ["tarot", 0],
  "qian": ["hex", 1], "kun": ["hex", 2], "kan": ["hex", 29], "li": ["hex", 30],
  "qian15": ["hex", 15], "ge": ["hex", 49], "jin": ["hex", 35], "gen": ["hex", 52],
  "fehu": ["rune", "fehu"], "algiz": ["rune", "algiz"], "isa": ["rune", "isa"],
  "sowilo": ["rune", "sowilo"], "raidho": ["rune", "raidho"],
  "perthro": ["rune", "perthro"], "uruz": ["rune", "uruz"]
};

/* ---- events 情境事件 (§5.3) — demand scales with depth in tower.js ---- */
FQ.TOWER_EVENTS = [
  /* 风物 scenery — gentle, resource-flavored */
  { id: "spring", type: "scenery", ic: "⛲", demand: 2, risk: 0,
    zh: "山腰灵泉", en: "Hillside Spring",
    tZh: "塔身裂隙渗出清泉，泉底沉着旅人掷入的许愿钱。", tEn: "A spring seeps from the tower's seam; wish-coins glint at the bottom.",
    win: [{ op: "hp", v: 1 }, { op: "coins", v: 3 }], lose: [{ op: "coins", v: -1 }] },
  { id: "shrine", type: "scenery", ic: "🛕", demand: 2, risk: 0,
    zh: "无名小龛", en: "Nameless Shrine",
    tZh: "半塌的神龛看不出供奉何方神明，香炉犹温。", tEn: "A half-fallen shrine to no god you can name; the censer is still warm.",
    win: [{ op: "dust", v: 1 }, { op: "coins", v: 2 }], lose: [{ op: "coins", v: -1 }] },
  { id: "library", type: "scenery", ic: "📚", demand: 3, risk: 0,
    zh: "残卷书房", en: "Ruined Library",
    tZh: "散落的星图与卦书里也许夹着前人的批注。", tEn: "Loose star-charts and hexagram scrolls — perhaps annotated by those before you.",
    win: [{ op: "omenTrue", v: 1 }, { op: "coins", v: 3 }], lose: [{ op: "omenHide" }] },
  { id: "garden", type: "scenery", ic: "🌸", demand: 3, risk: 0,
    zh: "悬空花园", en: "Hanging Garden",
    tZh: "塔外飘着一座失重的花园，梅枝正落下今年第一朵花。", tEn: "A weightless garden drifts outside; the plum drops its first blossom of the year.",
    win: [{ op: "hp", v: 2 }], lose: [{ op: "hp", v: -1 }] },
  { id: "echo", type: "scenery", ic: "🪞", demand: 3, risk: 0,
    zh: "回音镜厅", en: "Hall of Echoing Mirrors",
    tZh: "镜中人比你慢半拍。它抬手时，你的行囊轻了一分。", tEn: "Your reflection lags half a beat; when it raises a hand, your pack feels lighter.",
    win: [{ op: "coins", v: 4 }], lose: [{ op: "coins", v: -2 }] },

  /* 交涉 parley — argue with symbols */
  { id: "tollkeeper", type: "parley", ic: "🧌", demand: 5, risk: 1,
    zh: "阶前收税人", en: "The Stair-Toll Keeper",
    tZh: "巨人横坐阶上：「以你的『道理』付账，或以金付。」", tEn: "A giant blocks the stair: 'Pay in reasons — or in coin.'",
    win: [{ op: "coins", v: 5 }], lose: [{ op: "coins", v: -5 }] },
  { id: "merchant-ghost", type: "parley", ic: "👻", demand: 4, risk: 1,
    zh: "商魂讨价", en: "A Merchant's Ghost",
    tZh: "亡故的行商仍在原地摆摊，非要与你论一场旧价。", tEn: "A dead trader still keeps his stall, insisting on haggling an old price.",
    win: [{ op: "coins", v: 4 }, { op: "dust", v: 1 }], lose: [{ op: "coins", v: -3 }] },
  { id: "sphinx", type: "parley", ic: "🦁", demand: 6, risk: 1,
    zh: "斯芬克斯之问", en: "The Sphinx's Question",
    tZh: "「何物晨四足、午二足、暮三足？」它等你以符号作答。", tEn: "'What walks on four legs, then two, then three?' She waits for your symbols to answer.",
    win: [{ op: "dust", v: 2 }, { op: "coins", v: 3 }], lose: [{ op: "hp", v: -2 }] },
  { id: "watcher", type: "parley", ic: "🦉", demand: 5, risk: 1,
    zh: "守层枭人", en: "The Owl Warden",
    tZh: "枭首人身的守卫核对名册：「此层不见你的名字。」", tEn: "An owl-headed warden checks the ledger: 'Your name is not on this floor.'",
    win: [{ op: "coins", v: 3 }, { op: "hp", v: 1 }], lose: [{ op: "hp", v: -1 }, { op: "coins", v: -2 }] },
  { id: "rival", type: "parley", ic: "🧙", demand: 6, risk: 1,
    zh: "同行论法", en: "A Rival Diviner",
    tZh: "另一位登塔人拦路论法，要比一比谁的传统更灵。", tEn: "Another climber bars the way, keen to prove whose tradition reads truer.",
    win: [{ op: "dust", v: 2 }], lose: [{ op: "coins", v: -3 }] },

  /* 险境 peril — the gamble events (坎 loves these) */
  { id: "chasm", type: "peril", ic: "🌉", demand: 6, risk: 2,
    zh: "断桥之跃", en: "The Broken Bridge",
    tZh: "半座桥悬在雾上。跳，或者绕三层远路。", tEn: "Half a bridge hangs over the fog. Leap — or lose three floors of road.",
    win: [{ op: "coins", v: 6 }, { op: "dust", v: 1 }], lose: [{ op: "hp", v: -3 }] },
  { id: "vault", type: "peril", ic: "🗝️", demand: 7, risk: 2,
    zh: "封印宝库", en: "The Sealed Vault",
    tZh: "库门上的封条写着警告，门缝里透出金光。", tEn: "The seal on the vault door is a warning; gold light leaks through the crack.",
    win: [{ op: "coins", v: 9 }], lose: [{ op: "hp", v: -2 }, { op: "curseRand" }] },
  { id: "stormwall", type: "peril", ic: "🌪️", demand: 6, risk: 2,
    zh: "风暴回廊", en: "The Storm Gallery",
    tZh: "回廊里卷着不散的风暴，风眼中悬着一枚符号。", tEn: "A storm coils in the gallery; something glints inside its eye.",
    win: [{ op: "coins", v: 5 }, { op: "hp", v: 1 }], lose: [{ op: "hp", v: -3 }] },
  { id: "gambler", type: "peril", ic: "🎲", demand: 5, risk: 2,
    zh: "赌骨人", en: "The Bone Gambler",
    tZh: "老者摇着骨骰：「押上你的盘缠，或者你的胆子。」", tEn: "An old man rattles bone dice: 'Stake your purse — or your nerve.'",
    win: [{ op: "coinsRand", v: [4, 14] }], lose: [{ op: "coins", v: -6 }] },
  { id: "serpent", type: "peril", ic: "🐉", demand: 7, risk: 2,
    zh: "盘塔之蟒", en: "The Tower Serpent",
    tZh: "巨蟒缠着塔身酣睡，鳞间嵌着旅人的遗物。", tEn: "A great serpent sleeps coiled round the tower, relics wedged between its scales.",
    win: [{ op: "coins", v: 7 }, { op: "dust", v: 1 }], lose: [{ op: "hp", v: -3 }, { op: "coins", v: -2 }] },

  /* 奇遇 wonder — rare gifts, no demand check */
  { id: "comet", type: "wonder", ic: "☄️", demand: 0, risk: 0,
    zh: "拂塔彗星", en: "A Comet Grazes the Tower",
    tZh: "彗尾扫过窗棂，落下一撮尚温的星尘。", tEn: "The comet's tail brushes the sill, leaving a pinch of warm stardust.",
    win: [{ op: "dust", v: 2 }] },
  { id: "pilgrim", type: "wonder", ic: "🚶", demand: 0, risk: 0,
    zh: "下行的朝圣者", en: "A Pilgrim Descending",
    tZh: "一位从塔顶下来的朝圣者与你交换了行囊里最轻的东西。", tEn: "A pilgrim coming down trades you the lightest thing in her pack.",
    win: [{ op: "symbolGift" }] },
  { id: "aurora", type: "wonder", ic: "🌌", demand: 0, risk: 0,
    zh: "层间极光", en: "Aurora Between Floors",
    tZh: "极光在两层之间流淌，照见你还未走的路。", tEn: "An aurora pours between floors, lighting the road you have not walked.",
    win: [{ op: "peek" }, { op: "hp", v: 1 }] },
  { id: "beacon", type: "wonder", ic: "🕯️", demand: 0, risk: 0,
    zh: "长明灯龛", en: "The Undying Lamp",
    tZh: "一盏灯守着阶角，据说添过灯油的人不会迷路。", tEn: "A lamp keeps the stair's corner; those who feed its oil, they say, never lose the way.",
    win: [{ op: "omenTrue", v: 2 }, { op: "coins", v: 2 }] }
];

/* ---- 命劫 ordeals at floors 4/8/12 (§5.3) ----
   `need` is tracked across 3 rounds; check ids are implemented in tower.js */
FQ.TOWER_ORDEALS = [
  { id: "storm", ic: "🌊", zh: "风暴劫", en: "Ordeal of Storms",
    tZh: "整层塔泡在一场不肯过去的海难里。三回合内，打出水系符号 ≥2，或打出埃尔哈兹。",
    tEn: "This floor is drowned in a shipwreck that will not end. Within 3 rounds, play ≥2 water symbols — or Algiz.",
    needZh: "水系 ×2 或 ᛉ", needEn: "Water ×2 or ᛉ", check: "water2" },
  { id: "toll", ic: "🪙", zh: "关税劫", en: "Ordeal of Tariffs",
    tZh: "亡国的税吏在此复算所有旧账。三回合内，累计力量 ≥12，或缴纳 10 金。",
    tEn: "The dead empire's taxmen audit every old debt. Within 3 rounds, total power ≥12 — or pay 10 coin.",
    needZh: "累计力量 12 或 10 金", needEn: "Σpower ≥12 or pay 10", check: "power12" },
  { id: "plague", ic: "🦠", zh: "瘟疫劫", en: "Ordeal of Plague",
    tZh: "疫气沿阶而上。三回合内，打出生机符号（星星/死神/坤/乌鲁兹）≥1 且累计力量 ≥9。",
    tEn: "Miasma climbs the stairs. Within 3 rounds, play ≥1 life symbol (Star/Death/Kūn/Uruz) and total power ≥9.",
    needZh: "生机符号 + 力量 9", needEn: "Life symbol + Σpower 9", check: "life9" },
  { id: "suspicion", ic: "🗡️", zh: "猜忌劫", en: "Ordeal of Suspicion",
    tZh: "塔在此层学会挑拨离间。三回合内，触发至少一次跨文明「对照」共鸣以证同心。",
    tEn: "Here the tower sows discord. Within 3 rounds, spark at least one cross-civilization Contrast resonance.",
    needZh: "对照共鸣 ×1", needEn: "Contrast ×1", check: "contrast1" }
];

/* helpers */
FQ.towerSym = id => FQ.TOWER_SYMBOLS.find(s => s.id === id) || FQ.TOWER_CURSES.find(c => c.id === id);
FQ.towerIsCurse = id => id.startsWith("c-");
