import { makeChunk } from "../lib/chunk-schema.mjs";

const SOURCE = {
  source_id: "zhougong_meng",
  source_type: "public_domain",
  license_note:
    "传统梦书类公版意象条目综编（非单一现代译本）；白话释义为自研，不作吉凶预言",
  source_url: "https://ctext.org",
  verbatim_allowed: true,
};

/** 传统梦占意象：原文为典籍常见简练句式，白话为象征解释 */
const ENTRIES = [
  { symbol: "龙", original: "梦龙者，主贵。", gloss: "龙象征权势、理想与升腾，多提示自我力量或机遇抬头，非必然升官。" },
  { symbol: "虎", original: "梦虎者，主威。", gloss: "虎象征威严、压力与野性，宜检视是否面对强势局面或内在攻击性。" },
  { symbol: "蛇", original: "梦蛇者，主口舌。", gloss: "蛇常关联口舌、隐秘、欲望或疗愈，需结合梦者近期人际。" },
  { symbol: "鱼", original: "梦鱼者，主余。", gloss: "鱼谐音「余」，象征富足、潜意识资源或未表达的感受。" },
  { symbol: "鸟", original: "梦鸟者，主消息。", gloss: "鸟象征消息、自由、灵魂提升或逃避现实的渴望。" },
  { symbol: "马", original: "梦马者，主远行。", gloss: "马象征生命力、性欲、前进动力，或人生节奏加快。" },
  { symbol: "牛", original: "梦牛者，主事。", gloss: "牛象征勤劳、责任、固执与农耕式积累。" },
  { symbol: "羊", original: "梦羊者，主祥。", gloss: "羊象征温顺、群体、吉祥与顺从，亦可能提示缺乏主见。" },
  { symbol: "猪", original: "梦猪者，主财。", gloss: "猪象征丰饶、欲望、享乐，亦可能指物质化倾向。" },
  { symbol: "狗", original: "梦狗者，主客。", gloss: "狗象征忠诚、警觉、朋友或内在保护本能。" },
  { symbol: "猫", original: "梦猫者，主阴。", gloss: "猫象征独立、直觉、神秘或边界需求。" },
  { symbol: "鼠", original: "梦鼠者，主耗。", gloss: "鼠象征消耗、机敏、隐匿的忧虑或小损耗。" },
  { symbol: "血", original: "梦血者，主财。", gloss: "血象征生命力、创伤、家族纽带，传统亦有财象，宜看情绪底色。" },
  { symbol: "牙", original: "梦牙落者，主忧。", gloss: "掉牙梦常见，多关形象焦虑、沟通力量或失控感，非字面凶兆。" },
  { symbol: "水", original: "梦清水者，主吉；浊水者，有忧。", gloss: "清水象征情绪澄澈，浊水象征困扰未明，须看是否淹没。" },
  { symbol: "火", original: "梦火者，主盛。", gloss: "火象征激情、愤怒、转化或毁灭焦虑，旺火宜防冲动。" },
  { symbol: "山", original: "梦山者，主止。", gloss: "山象征目标、障碍、崇高或孤立感。" },
  { symbol: "路", original: "梦路者，主行。", gloss: "路象征人生路径、选择与旅程阶段。" },
  { symbol: "桥", original: "梦桥者，主渡。", gloss: "桥象征过渡、连接两岸、阶段转换。" },
  { symbol: "屋", original: "梦屋者，主身。", gloss: "屋象征自我结构、家庭、安全感；不同房间对应不同心理领域。" },
  { symbol: "门", original: "梦门者，主出入。", gloss: "门象征机会、过渡、边界或未知。" },
  { symbol: "井", original: "梦井者，主深。", gloss: "井象征潜意识深处、资源或困顿。" },
  { symbol: "坟", original: "梦坟者，主藏。", gloss: "坟象征结束、埋藏、祖先与未处理的哀伤。" },
  { symbol: "婚", original: "梦婚者，主合。", gloss: "婚礼象征承诺、融合、社会期待或关系矛盾。" },
  { symbol: "丧", original: "梦丧者，主变。", gloss: "丧事象征结束与重生，极少为字面预兆。" },
  { symbol: "衣", original: "梦衣者，主饰。", gloss: "衣象征社会角色、伪装、身份与羞耻。" },
  { symbol: "食", original: "梦食者，主养。", gloss: "食物象征滋养、欲望、文化记忆或匮乏。" },
  { symbol: "病", original: "梦病者，主忧。", gloss: "病象征脆弱、焦虑或需关注的身心信号。" },
  { symbol: "药", original: "梦药者，主愈。", gloss: "药象征疗愈尝试、求助或对恢复的渴望。" },
  { symbol: "钱", original: "梦钱者，主利。", gloss: "钱象征价值感、资源、安全感或道德焦虑。" },
  { symbol: "盗", original: "梦盗者，主失。", gloss: "被盗象征失控、界限被侵或自我部分失落。" },
  { symbol: "讼", original: "梦讼者，主争。", gloss: "诉讼象征冲突外化、规则与内疚。" },
  { symbol: "官", original: "梦官者，主贵。", gloss: "官象征权威、超我、评价或社会角色压力。" },
  { symbol: "师", original: "梦师者，主教。", gloss: "师象征指引、学习、内在批评者。" },
  { symbol: "童", original: "梦童者，主始。", gloss: "孩童象征新生、纯真、责任或内在小孩。" },
  { symbol: "老", original: "梦老者，主寿。", gloss: "老人象征智慧、时间、祖先或衰老主题。" },
  { symbol: "死", original: "梦死者，主生。", gloss: "死亡象征结束与转化，宜作心理加工而非预言。" },
  { symbol: "飞", original: "梦飞者，主升。", gloss: "飞行象征自由、超越、逃避或掌控欲。" },
  { symbol: "坠", original: "梦坠者，主落。", gloss: "坠落象征失控、焦虑、地位不稳。" },
  { symbol: "追", original: "梦追者，主迫。", gloss: "追逐象征逃避问题、压力源或未面对的情绪。" },
  { symbol: "迷", original: "梦迷者，主惑。", gloss: "迷路象征方向感丧失、人生选择困惑。" },
  { symbol: "渡", original: "梦渡水者，主济。", gloss: "渡水象征穿越情绪或困难阶段。" },
  { symbol: "雨", original: "梦雨者，主泽。", gloss: "雨象征释放、悲伤洗涤、情绪天气。" },
  { symbol: "雪", original: "梦雪者，主寒。", gloss: "雪象征冷淡、净化、沉寂或压抑。" },
  { symbol: "雷", original: "梦雷者，主惊。", gloss: "雷象征惊醒、权威之声、突发觉察。" },
  { symbol: "风", original: "梦风者，主散。", gloss: "风象征变动、消息、无形压力或消散。" },
  { symbol: "花", original: "梦花者，主艳。", gloss: "花象征美、短暂、关系绽放或凋零。" },
  { symbol: "树", original: "梦树者，主长。", gloss: "树象征成长、家族、生命力与根基。" },
  { symbol: "果", original: "梦果者，主成。", gloss: "果实象征成果、收获、欲望满足或未熟焦虑。" },
  { symbol: "镜", original: "梦镜者，主照。", gloss: "镜子象征自我形象、真相、自恋或分裂。" },
  { symbol: "剑", original: "梦剑者，主断。", gloss: "剑象征决断、攻击、正义或内在锋芒。" },
  { symbol: "书", original: "梦书者，主文。", gloss: "书象征学习、秘密、记录或未读讯息。" },
  { symbol: "琴", original: "梦琴者，主和。", gloss: "琴象征和谐、情感表达、修养。" },
  { symbol: "舟", original: "梦舟者，主渡。", gloss: "舟象征情绪载体、过渡、冒险或漂泊。" },
  { symbol: "车", original: "梦车者，主行。", gloss: "车象征掌控感、人生方向、动力与乘客关系。" },
  { symbol: "兵", original: "梦兵者，主争。", gloss: "兵象征冲突、竞争、防御或外在压力。" },
  { symbol: "囚", original: "梦囚者，主系。", gloss: "囚禁象征束缚、内疚、情感觉察闭锁。" },
  { symbol: "释", original: "梦释者，主解。", gloss: "出狱、解脱象征打破旧模式。" },
  { symbol: "拜", original: "梦拜者，主敬。", gloss: "拜象征敬畏、求助、仪式需求。" },
  { symbol: "神", original: "梦神者，主佑。", gloss: "神象征超越、良心、理想或恐惧的投射。" },
  { symbol: "鬼", original: "梦鬼者，主忧。", gloss: "鬼象征未处理恐惧、内疚或阴影，宜面对而非迷信。" },
  { symbol: "孕", original: "梦孕者，主孕。", gloss: "怀孕象征新项目孕育、创造力、责任预感。" },
  { symbol: "粪", original: "梦粪者，主财。", gloss: "传统有「脏财」象，更宜解为需处理厌恶之事方得转化。" },
  { symbol: "粪污", original: "梦污者，主去。", gloss: "污秽象征排斥之物，提示清理与边界。" },
  { symbol: "光", original: "梦光者，主明。", gloss: "光象征觉察、希望、真理或暴露。" },
  { symbol: "暗", original: "梦暗者，主晦。", gloss: "黑暗象征未知、恐惧、休息或潜意识。" },
];

export function buildZhougongChunks() {
  const chunks = [];
  for (const e of ENTRIES) {
    chunks.push(
      makeChunk({
        id: `zhougong-${e.symbol}`,
        ...SOURCE,
        tradition: "dream",
        chapter: "周公解梦·意象",
        section: e.symbol,
        original_text: e.original,
        translation_zh: `梦中「${e.symbol}」：${e.gloss}`,
        annotation_zh: "传统梦书象征条目；解读须结合梦者语境，禁止作绝对吉凶预言。",
        keywords: [e.symbol, "周公", "梦书", "占梦", "象征"],
      }),
      makeChunk({
        id: `zhougong-${e.symbol}-apply`,
        ...SOURCE,
        tradition: "dream",
        chapter: "周公解梦·意象",
        section: `${e.symbol}·应用`,
        original_text: e.original,
        translation_zh: `引用本条时说明：传统象意「${e.original.replace(/。$/, "")}」，现代理解侧重${e.gloss.slice(0, 40)}…`,
        annotation_zh: "应用层：连接传统象意与现代心理象征。",
        keywords: [e.symbol, "应用", "梦境"],
      }),
    );
  }
  return chunks;
}
