extends RefCounted

## Cross-language parity: Rng must reproduce Atlas seed.ts bit-for-bit.
## Fixture is generated by tools/parity/gen_rng_fixture.mjs from the actual
## TypeScript source. CODE_PLAN.md §10 step 1 — get this right and the whole
## class of "why did two runs differ" bugs never appears.

func run() -> bool:
	var f := FileAccess.open("res://tools/parity/rng_fixture.json", FileAccess.READ)
	assert(f != null, "rng_fixture.json missing — run tools/parity/gen_rng_fixture.mjs")
	var fx: Dictionary = JSON.parse_string(f.get_as_text())
	var failures := 0

	for c in fx["cases"]:
		var seed: String = c["seed"]
		var h := Rng.hash_seed(seed)
		if h != int(c["hash"]):
			printerr("hash mismatch seed=%s got=%d want=%d" % [seed, h, int(c["hash"])])
			failures += 1
			continue
		var r := Rng.new(seed)
		for i in (c["first16"] as Array).size():
			var got := r.next()
			var want: float = c["first16"][i]
			if absf(got - want) > 1e-15:
				printerr("value mismatch seed=%s i=%d got=%.17f want=%.17f" % [seed, i, got, want])
				failures += 1
				break

	# fork() must yield independent streams — the guarantee that lets one
	# system's draw count not leak into another's.
	var a := Rng.new("x").fork("market")
	var b := Rng.new("x").fork("storm")
	if is_equal_approx(a.next(), b.next()):
		printerr("fork() produced identical streams for different labels")
		failures += 1

	print("test_rng: %s" % ("PASS" if failures == 0 else "FAIL (%d)" % failures))
	return failures == 0
