/* 师承 · The Lineage (GDD §4.9) — divination is LEARNED, not given.
   Each art belongs to a teacher who belongs to a place on the road.
   Reach the place → the teacher appears → pass the trial → the art is yours.
   Until then the realm stays dark, and roads that demand it stay shut. */
window.FQ = window.FQ || {};

/* trial.kind is resolved by quest.js; `need` is the passing condition text */
FQ.MENTORS = [
  {
    method: "tarot", at: "venice", auto: true, ic: "🔮",
    zh: "制牌人 老马蒂欧", en: "Matteo the Cardmaker",
    civZh: "威尼斯 · 里亚尔托桥下", civEn: "Venice · beneath the Rialto",
    introZh: "临行前夜，父亲带你去见一位制牌的老人。里亚尔托桥下的这间作坊已经传了三代，墙上挂满了未完成的牌面——教皇、死神、倒吊人，每一张都是手绘的蛋彩画，颜料里掺着从塞浦路斯运来的矿物粉末。老马蒂欧把一叠厚纸推过桌面，袖口扫过桌上的铜币：『这些牌不算命——它们只是把你已经知道的事，摆成看得见的样子。我祖父在博洛尼亚大学学哲学的时候，教授告诉他：宇宙是一张四面都写满了符号的纸。牌就是这张纸的碎片。带上它们——路上没人陪你说话的时候，就跟牌说。它们听过的故事比大都的史官还多。至于钱——威尼斯人收钱，但制牌人收的是你把牌画清楚的心。』",
    introEn: "The night before departure your father takes you to an old cardmaker. This workshop beneath the Rialto has stood three generations; unfinished cards hang on every wall — the Pope, Death, the Hanged Man — each one tempera on board, the pigments ground from minerals shipped out of Cyprus. Old Matteo pushes a stack of hand-painted cards across the table, his sleeve brushing a few copper coins: 'These don't tell fortunes. They lay out what you already know, where you can see it. My grandfather studied philosophy at Bologna, and his master told him: the cosmos is a page written on all four sides with signs. A deck is just a torn corner of that page. Take them — when no one on the road will talk to you, talk to these. They've heard more stories than all the record-keepers in Khanbaliq. As for money — Venetians take coin, but a cardmaker takes the will to paint clear.'",
    storyZh: "马蒂欧不是威尼斯人。他的祖父是博洛尼亚的抄经僧，为一份手稿跟主教吵翻之后，带着染料和刷子顺着运河漂到了威尼斯。抄经的规矩——每一笔不能回头——后来变成了制牌的手艺：每一张牌画一笔是一笔，不描不补。他把这个规矩教给了儿子，儿子教给了孙子。如今「小」马蒂欧七十岁了，他的牌在佛罗伦萨卖得比在威尼斯还贵，但他不肯离开桥下的作坊。『这座桥下面流水的声音，比任何教堂的管风琴都好听，』他说，『而且不找你要什一税。』作坊里常年有蛋清、塞浦路斯矿粉与松节油的气味；冬日他穿一件红呢长袍，袖口宽得能藏一封密信，夏天则只剩麻衬衫。他收学徒从不收月钱——只收「一顿像样的晚饭」，最好是咸鱼配淡酒。他一生只收过两个学徒——你是第三个，也是唯一一个要带着他的牌走到帝国另一头的人。临行前他叮嘱：法兰克人爱问「这牌准不准」——你只答「它摆得清楚」。准不准是神的事，清楚是手艺的事。里亚尔托的潮汐涨落，他把作坊的门槛磨得发亮——学徒进门先擦鞋，出牌前先洗手，像进教堂。学徒进门先擦鞋，出牌前先洗手——桥下的作坊规矩，比教堂还严。",
    storyEn: "Matteo is not a Venetian. His grandfather was a manuscript monk in Bologna who quarreled with his bishop over an illumination, packed his brushes and dyes, and drifted down the canals to Venice. The monastic rule — every stroke final, no going back — became the family craft of cardmaking: each image laid down once, never retouched. He taught his son, his son taught his. Now 'young' Matteo is seventy; his cards sell dearer in Florence than in Venice, yet he will not leave the shop beneath the bridge. 'The sound of water under this bridge is finer than any church organ,' he says, 'and it doesn't ask for tithes.' The shop always smells of egg-white, Cypriot mineral dust and turpentine; in winter he wears a scarlet wool robe with sleeves wide enough to hide a sealed letter, in summer only a linen shirt. He never charges apprentices monthly — only 'one decent supper,' preferably salt-fish and thin wine. He has taken only two apprentices in his life. You are the third — and the only one who will carry his cards to the other end of the empire. Before you leave he warns: Franks love to ask whether the cards are 'true.' Answer only: 'They lay things clear.' Truth is God's business; clarity is craft. The Rialto tides have polished his threshold bright — apprentices wipe their shoes on entry and wash hands before painting, as if entering a church. Apprentices wipe shoes on entry and wash hands before painting — rules under the bridge stricter than church.",
    trial: { kind: "tarotDraw", need: 1,
      taskZh: "抽一张牌，认出它的正逆", taskEn: "Draw one card; know it upright from reversed" },
    gradZh: "「记住：逆位不是坏事，是同一件事的另一张脸。」老人把牌塞进你怀里，转身回作坊了。",
    gradEn: "'Remember: reversed is not ill — it is the same thing wearing its other face.' He presses the deck into your coat and returns to his workshop."
  },
  {
    method: "lenormand", at: "venice", ic: "🃁",
    zh: "牌铺女儿 卡特琳娜", en: "Caterina of the Card Shop",
    civZh: "威尼斯 · 制牌作坊", civEn: "Venice · the card workshop",
    introZh: "老马蒂欧的女儿在后间裁另一副牌——三十六张，画的全是近处的东西：信、船、钥匙、老鼠。『大牌问命，小牌问事。』她把一张画着百合花的牌放在船牌旁边：『你看，花挨着船——今天要送一封信给一个爱你的人。大牌不会告诉你这种事，因为大牌觉得儿女情长不配占一页命运。但一个人一生里最多的就是这种小事。你要走的是路，不是命——带这副。』（几百年后，人们会用一位法国女占者的名字称呼它，但第一副画了信的牌，是在这间昏暗的后屋里，由这个不识字但认得出所有人脸上到底是喜悦还是忧愁的女孩画出来的。）",
    introEn: "In the back room old Matteo's daughter cuts a different deck — thirty-six cards of near things: letters, ships, keys, mice. 'The big cards ask about fate. These ask about Tuesday.' She lays a lily beside a ship: 'Look — the flower beside the vessel. Today you will send a letter to someone who loves you. The big cards would never speak of this, because they think a love letter is too small to fill a page of destiny. But a life is made of such small things.' She taps the deck. 'You're walking a road, not a fate — take these.' (Centuries later they will bear a French fortune-teller's name, but the first deck with a letter on it was painted in this dim back room by a girl who could not read, but could always tell whether the person sitting across from her was joyful or sorrowful.)",
    storyZh: "卡特琳娜的手艺不是父亲教的。十三岁那年，一个上了年纪的吉普赛女人在作坊门口避雨，从怀里掏出一副用皮绳扎着的旧牌，替排队的顾客看了一下午的手相。临走前她给卡特琳娜留了半副牌——已经旧得看不清图案了，但卡特琳娜照着那些模糊的轮廓重画了一整套，还加上了威尼斯日常生活里最常被提起的物件：信、船、钥匙、老鼠、百合。后来她听码头上的水手说，这种三十六张的牌在日耳曼地区到处都有，但她不信——「日耳曼又没有我们的船。他们的钥匙也跟我们不一样——我们的钥匙是铁打的，他们的多半是木头。」她现在二十六岁，每天替码头工人和面包房老板娘翻牌，收一枚铜币——从不少收一文，也从不加价给富商。她穿一件洗得发白的蓝围裙，发髻上别着父亲不要的骨牌碎片。她攒下来的钱不是给自己，是给运河对岸那个瘸腿的抄经生——他替她写牌上她不会写的拉丁字。她对法兰克人的态度很简单：能付钱的就翻，爱问「为什么」的就让他们看两张成对的牌——「牌与牌之间才有话，一张牌只会喊。」雨天她把牌摊在窗下，听桨声数拍子；她说小牌要听近处的响，大牌才听远处的雷。",
    storyEn: "Caterina did not learn her craft from her father. When she was thirteen, an aging Romani woman sheltered from the rain in the shop doorway, drew from her coat a deck bound in leather thong, and read palms for the queue all afternoon. Before leaving, she gave Caterina half a deck — so worn the pictures were barely visible — but Caterina recopied every smudged outline and added the objects most often mentioned in Venetian daily talk: letters, ships, keys, mice, lilies. Later, sailors at the docks told her that these thirty-six-card decks were common in the German lands. She does not believe it: 'Germany has none of our ships. And their keys are different — ours are iron, theirs are mostly wood.' She is twenty-six now. Each day she turns cards for dockworkers and bakers' wives — one copper, never a copper less for the poor, never a copper more for the rich. She wears a washed-out blue apron and pins a discarded bone card-chip in her hair. She saves the money, not for herself, but for the lame scribe across the canal — he writes the Latin words on her cards that she cannot. Her view of Franks is simple: if they can pay, she turns; if they ask 'why,' she shows them a pair — 'Meaning lives between two cards. One card only shouts.' On rainy days she spreads the cards under the window and counts the oar-strokes; near sounds for small cards, far thunder for the great ones.",
    trial: { kind: "lenPair", need: 2,
      taskZh: "翻开三张，说出成对的两张", taskEn: "Turn three; name the two that speak together" },
    gradZh: "「牌与牌之间才有话。」卡特琳娜把牌扎成一小捆，用麻绳系上。",
    gradEn: "'The meaning lives between two cards, never in one.' She binds the deck with twine."
  },
  {
    method: "runes", at: "acre", ic: "ᚠ",
    zh: "瓦良格卫兵 哈拉尔", en: "Haraldr the Varangian",
    civZh: "阿卡 · 城墙夜哨", civEn: "Acre · the night watch",
    introZh: "阿卡城墙上，一个金发巨汉守着夜哨。他是从米克拉加德——也就是你们基督徒管叫君士坦丁堡的那个城市——南下的瓦良格人。他不信基督，也不信穆罕默德，但他腰间挂着一只从不离身的鹿皮袋。『我祖母说，字母是奥丁吊在世界之树上九夜换来的。九个夜晚不吃不喝，侧身挂在树枝间，直到树下的水面上浮现出这些图案。奥丁拿一只眼睛换了一个女人，拿这九个夜晚换了所有的话。你要看看吗？——反正天亮前没别的事做，而鞑靼人今晚不会攻城——我摇过石头了。』",
    introEn: "On the walls of Acre a fair-haired giant keeps watch — a Varangian come south from Miklagard, the city you Christians call Constantinople. He holds neither the Cross nor the Prophet's creed, but at his belt hangs a deerskin pouch he never parts with. 'My grandmother said the letters were bought by Odin, nine nights hanging from the world-tree. Nine nights without food or drink, slung sideways among the branches, until the shapes rose up from the water beneath the tree. Odin traded one eye for a woman, and nine nights for every word there is. Want to see? Nothing else to do before dawn, and the Tartars won't attack tonight — I shook the stones already.'",
    storyZh: "哈拉尔的祖母是挪威北边一个渔村的「符文妇」——村里没有人识字，但人人都来找她摸一摸鹿皮袋里的石头。她不给别人刻符文，只刻给自己的孙子。哈拉尔十五岁那年离开渔村，划着一条抢来的撒克逊长船先去了英格兰，又顺着法兰西海岸到了西西里，最后被君士坦丁堡的瓦良格卫队招募。他在皇城当过二十年御前侍卫，见过真正的金袍皇帝跪在圣索菲亚大教堂的大理石地面上流泪。但他最怀念的是十三岁那年的一个下午——祖母把刚刻好的一块符文放进他手心，说：『这一块是安苏兹，奥丁的气息。不要让只会打仗的人堵住你的嘴巴。』他后来在很多次战斗中靠这句话活了下来——不是因为它告诉了他什么，而是因为每次摸到这块石头，他就听见祖母在说话。在阿卡城墙上，他仍穿瓦良格式的皮甲与毛皮披肩，腰间挂着从不离身的鹿皮袋；基督徒叫他异教徒，穆斯林叫他北蛮——他只笑，说石头比两种经书都更早到这里。他不收钱教符文，只收「一壶不掺水的酒，和一句真话」。夜哨时他用拇指摩挲安苏兹那块石，城下灯火像一串没刻完的符——他说阿卡的石头也听得懂北风。他教符文不收银，只收一壶不掺水的酒与一句真话——假话比敌箭更伤人。",
    storyEn: "Haraldr's grandmother was a rune-woman in a fishing village in the Norwegian north — no one in the village could read, but everyone came to touch the stones in her deerskin pouch. She carved runes for no one but her grandson. At fifteen, Haraldr left the village, rowed a captured Saxon longship first to England, then down the Frankish coast to Sicily, and was finally recruited into the Varangian Guard at Constantinople. He spent twenty years as an Imperial bodyguard and saw gold-robed emperors weep on the marble floor of the Hagia Sophia. But what he remembers most is an afternoon when he was thirteen: his grandmother pressed a freshly carved rune into his palm and said, 'This one is Ansuz — Odin's breath. Do not let men who only know fighting close your mouth.' He has survived many battles because of that sentence — not for what it told him, but because every time he touches the stone, he hears his grandmother speaking. On Acre's walls he still wears Varangian leather and a fur cape, the deerskin pouch never off his belt; Christians call him heathen, Moslems call him North-barbarian — he only laughs, saying the stones arrived here before either book. He will not take coin for teaching runes — only 'a jug of unwatered wine, and one true sentence.' On night watch he rubs Ansuz with his thumb; lamps below look like unfinished runes — Acre's stones, he says, also understand the north wind. He takes no silver for runes — only unwatered wine and one true sentence; a lie wounds worse than an enemy arrow.",
    trial: { kind: "runeDraw", need: 3,
      taskZh: "自袋中取三枚石，念出其名", taskEn: "Draw three stones from the pouch and name them" },
    gradZh: "「石头不说话，是你在说话——石头只是让你慢下来听。」哈拉尔把鹿皮袋抛给你，回头继续望着海。",
    gradEn: "'The stones don't speak. You do — they only make you slow enough to hear it.' He tosses you the pouch and turns back to the sea."
  },
  {
    method: "astrodice", at: "tabriz", ic: "🎲",
    zh: "星家 帖必烈", en: "Tebrizi the Star-Reader",
    civZh: "大不里士 · 观星台", civEn: "Tabriz · the observatory",
    introZh: "大不里士城郊的观星台上，老帖必烈把三枚骨骰倒进一只打凹了的铜盘里。盘底蚀刻着十二星座的符号——那是他自己四十年前用硝酸画上去的，有几处已被骰子砸得模糊了。『星盘要算一夜，骰子只要一瞬——同一片天，穷人也问得起。行星是「什么」，星座是「怎样」，宫位是「在哪儿」。就这三件事——你记住这三件事，大不里士任何一个码头上的人都会愿意为你付上一枚第纳尔。』他顿了顿：『不过如果你付得起一晚的时间——我是说一整晚——我还可以教你怎么读真的星星。真正的星星不是黄道上的那些点，而是有颜色的。织女星是蓝的，心宿二是红的，像一块烧到一半的炭。』",
    introEn: "On the observatory high above Tabriz, old Tebrizi spills three bone dice into a beaten brass tray. The tray's floor is etched with the twelve zodiac signs — he drew them himself with acid forty years ago, and the dice have worn some of the lines nearly smooth. 'The astrolabe takes a night; the dice take a breath — the same sky, priced for the poor. Planet is what, sign is how, house is where. That is all there is — memorize those three and any man on the Tabriz docks will pay you a dinar.' He pauses. 'But if you can spare a night — and I mean a full night — I can also teach you to read the real stars. Not the dots on the zodiac. The ones with color. Vega is blue. Antares is red — like a coal burning down.'",
    storyZh: "帖必烈年轻时在马拉盖天文台做过十二年学徒。马拉盖——伊利汗国最伟大的科学机构——有十二道象限仪、一座直径十四肘的浑天仪，和一位名叫纳西尔丁·图西的大师。帖必烈给图西磨过镜片，抄过星表，还在他的葬礼上念过《古兰经》开篇章法蒂哈——虽然图西本人很可能没念过。他的左手食指缺了一截——那是他在调试浑天仪的铜环时被夹断的，他说这是他为天文学付出的「血税」。蒙古人入侵时烧了马拉盖的一部分藏书，帖必烈在废墟里扒出三本没烧完的星表，用骆驼皮包好带着。那三本星表现在还在他床下，每晚睡前翻一遍——他说星星会变慢，但纸上的数字不会。大不里士观星台夜里风硬，他裹一件靛蓝染的旧袍，头巾缠得像水手；白日则在巴扎里用三枚骨骰替码头苦力排「穷人也问得起」的天。他收一枚第纳尔教一夜真星，收半枚只教骰子——「骰子是给赶路人的；真星是给肯坐下来的人。」对法兰克人他并不傲慢：「你们的托勒密写得美，但没见过马拉盖的象限仪——美不等于准。」巴扎铜锤敲到后半夜，他仍抬头找织女那一点蓝——『骰子是捷径，蓝光才是师傅。』铜盘底的黄道纹被骰子砸模糊了几处——他说模糊处最该小心，天也有磨损。",
    storyEn: "As a young man Tebrizi spent twelve years as an apprentice at Maragha, the Ilkhanate's greatest scientific institution — twelve quadrants, an armillary sphere fourteen cubits across, and a master named Nasir al-Din al-Tusi. Tebrizi ground lenses for Tusi, copied star-tables for Tusi, and recited the Fatiha at Tusi's funeral — though Tusi himself probably never did. He is missing the top joint of his left index finger, crushed while adjusting the brass ring of the armillary; he calls it the blood-tax of astronomy. When the Mongols burned part of the Maragha library, Tebrizi pulled three unburnt star-tables from the rubble and wrapped them in camel leather. Those three books still lie under his bed; he turns their pages every night before sleep. Stars, he says, get slower with age — but the numbers on paper never do. At the Tabriz observatory the night wind is hard; he wraps an old indigo robe and winds his turban like a sailor; by day, in the bazaar, three bone dice serve dock-laborers a sky the poor can afford. One dinar buys a night of real stars; half a dinar buys only the dice — 'Dice for men in a hurry; true stars for men who will sit.' He is not arrogant toward Franks: 'Your Ptolemy writes beautifully — but he never saw Maragha's quadrants. Beauty is not the same as accuracy.' When bazaar hammers run past midnight he still looks up for Vega's blue — 'Dice are a shortcut; that blue is the master.' Zodiac lines on the brass tray are worn smooth by dice — wear, he says, is where the sky itself grows thin.",
    trial: { kind: "diceRoll", need: 1,
      taskZh: "掷出三骰，读出「何事 · 如何 · 何处」", taskEn: "Roll all three and read what · how · where" },
    gradZh: "帖必烈把骰子收进丝囊：「拿去。若你肯载我一程，我还教你看真的星。」",
    gradEn: "He drops the dice into a silk bag: 'Yours. And if you'll carry an old man east, I'll teach you the real stars too.'"
  },
  {
    method: "western", at: "hormuz", ic: "♈",
    zh: "海商星占 娜迪拉", en: "Nadira, Astrologer of the Port",
    civZh: "霍尔木兹 · 码头星占摊", civEn: "Hormuz · the quayside stall",
    introZh: "码头边一顶蓝布篷下，女子替出海的船工排星盘。她不是波斯人——她的祖母是亚美尼亚的基督徒，祖父是设拉子的穆斯林，她自己谁也说不清该算哪一教的。但这在霍尔木兹不算缺点——霍尔木兹每天有一百种颜色的帆，从一百种地方来。『你生在什么时候，海就用什么脾气对你——这不是迷信，是船工愿意信的东西。信了，他们才敢上船。』她把一张画着黄道圈的旧羊皮摊开，指着天蝎座的尾巴尖儿：『看见没——这一带叫「船桅藏针」，不是托勒密定的，是我定的。因为有一个水手每次走到这个星区就丢罗盘。我找了一辈子原因，没找到——但至少我给它取了个名字。』",
    introEn: "Under a blue awning a woman casts charts for departing sailors. She is not Persian — her grandmother was an Armenian Christian, her grandfather a Muslim from Shiraz, and she herself cannot say which house of God she belongs to. But at Hormuz this is no defect: Hormuz sees a hundred colors of sail every day, from a hundred places. 'The hour you were born is the temper the sea takes with you. Not truth — but what a sailor needs to believe before he'll board.' She spreads an old sheepskin chart stained with zodiac wheels and taps the tip of Scorpio's tail: 'See this spot? I call it Needle-in-the-Mast. Ptolemy didn't name it — I did. A sailor kept losing his compass at this degree of the sky. I have spent my life trying to find out why. So far, nothing. But at least I gave it a name.'",
    storyZh: "娜迪拉十六岁结过一次婚——嫁给了一个去印度的船主，公公是波斯老派的穆斯林，不让她在人前排星盘，更不让她收男人的钱。船主在第三年遇上风暴死了，船货具沉，只剩一箱子星图被浪冲回了码头。她抱着那箱湿透的纸在码头坐了一整夜，天亮时想明白了一件事：风暴不是因为她的星盘没算准——风暴根本就不管你是男的女的。她从此自己摆摊，收一个铜币翻一张盘——童叟无欺，男女同价。她的三个儿子都在码头上打短工，最小的一个只有十一岁，已经能凭肉眼认出木星的四颗月亮。霍尔木兹的热风能烤熟生肉；她的蓝布篷下常备枣、咸金枪鱼与洋葱——本地人的日常，也是她对远航者的饯行。她对缝合船从不隐瞒恐惧：「法兰克人爱铁钉，这里的船用椰索——看起来脆弱，却在浅滩上弯曲而不折。」『如果有一天你走到印度的戈尔孔达——』她忽然停住——『印度很远。比你的威尼斯远得多了。』她没有再说下去，但我后来听说她的丈夫当年就是从戈尔孔达起航的。她把羊皮星图用枣核压边，防热风卷走；出海的人若哭，她只加收半枚铜币，说『泪也占地方』。蓝布篷下常备枣与咸鱼饯行；她说霍尔木兹的风不认教派，只认帆收得够不够快。",
    storyEn: "Nadira married once, at sixteen — to a ship-owner bound for India. Her father-in-law was a Persian Moslem of the old school, who forbade her to cast charts in public, and certainly forbade her to take men's money. The ship-owner was taken by a storm in his third year at sea; the cargo sank entire, and the only thing the waves threw back was a chest of star-charts. She sat on the quay with that box of sodden paper all through the night, and by dawn she understood one thing: the storm had not come because her chart was wrong. The storm did not care whether you were a man or not. She has kept her own stall ever since — one copper, one chart, no haggling, same price for men and women alike. Her three sons work odd jobs on the docks; the youngest is eleven and can already pick out Jupiter's four moons with his naked eye. Hormuz's day-wind can cook raw meat; under her blue awning she keeps dates, salt tunny and onions — local fare, and her farewell to outbound crews. She never hides her fear of sewn ships: 'Franks love iron nails; here the boats are lashed with coir — they look frail, yet bend on the shoal instead of breaking.' 'If you ever walk as far as Golconda in India—' She stops. 'India is far. Farther than your Venice, much farther.' She did not finish. But later I heard that her husband had sailed from Golconda. She weights the sheepskin chart with date-pits against the hot wind; if a sailor weeps she adds half a copper — 'Tears take room on the chart too.' Under the blue awning she keeps dates and salt-fish for farewells; Hormuz wind, she says, knows no creed — only whether the sail came down fast enough.",
    trial: { kind: "westernCast", need: 1,
      taskZh: "以生辰定出太阳星座", taskEn: "Fix a sun sign from a birth date" },
    gradZh: "「记得报吉时也要报凶时。」娜迪拉在你手心画了一个圈，「星象骗人，占者不能骗人。」",
    gradEn: "'Speak the ill hours as well as the fair.' She draws a circle on your palm. 'The stars may mislead. The reader must not.'"
  },
  {
    method: "meihua", at: "pamir", ic: "🌸",
    zh: "西行僧 明远", en: "Mingyuan, the Westbound Monk",
    civZh: "帕米尔 · 雪线驿棚", civEn: "The Pamir · a shelter at the snowline",
    introZh: "雪线上的一间矮石棚里，一个汉地僧人正在烤几块冻得像石头一样的饼。他叫明远，从汴梁出发往西走了三年——他说他的上师托梦告诉他，须到「日没之处」寻一部失传的经书。他走到帕米尔时发现经书只是一个寓言，但已经不想回去了。『邵康节说，观梅落而知天机——不必等蓍草，不必备铜钱。此刻的数就是卦：驼铃响几声，你手边有几块柴。天机不在远处，在手边。』他掰了一小块饼放在火边，让饼上的冰慢慢化成水珠：『你们威尼斯也有失传的东西吗？——不用回答，你的脚步已经说了。人走路，总是为了找一种已经忘了的东西。』",
    introEn: "In a low stone shelter at the snowline, a monk from the Middle Kingdom toasts several cakes that have frozen to the hardness of stones. His name is Mingyuan; he has walked west from Bianliang for three years, having been told in a dream by his master to seek a lost scripture at 'the place where the sun sets.' By the time he reached the Pamir he knew the scripture was only a parable, but he no longer wished to return. 'Shao Yong watched plum blossoms fall and read the hour in them. No yarrow, no coins — the numbers of this moment are the hexagram. How many camel bells; how many sticks at your hand. Heaven's hinge is not far away. It is beside you.' He sets a sliver of frozen cake near the fire so the ice melts bead by bead. 'Does Venice have lost things too? — No, do not answer. Your footsteps have already answered. A person walks always in search of something they have already forgotten.'",
    storyZh: "明远不是寻常僧人。他年轻时在临安府的太学读过五年书，会背整部《左传》，也会用算筹解三次方程。三十岁那年秋天，他在西湖边看见一棵梅树忽然落尽了花——才九月，离该落花的时节还有四个月。他问遍了临安所有的花农和道士，没人能解释。他自己用算筹推了一整天，得出一个卦——「咸」。感也。不是花出了问题，是地气感召了天时。从那一天起他不再回太学，穿着一件补了七次的僧袍，一路向西走——不是去找经书，是去追那个让他看不懂预兆的谜底。如今他在帕米尔的雪线上一住就是几年，自己学会了烤饼、缝羊皮袍、在零下三十度的夜里不让水囊冻成冰。他说这些手艺比任何一部经书都实在——经书是写在纸上的，但他每天从手里学到的活计是写进了骨头里的。驿棚里他只收「半块饼」当谢礼——再多他便推回：「雪线上的人情，不能用金子量。」对法兰克人他好奇多于戒备：「你们的神钉在木头上；我们的天机落在梅花上——也许是同一场雪，两种脚印。」雪线驿棚的柴要数着烧；他起卦前先听驼铃几声，说『数不清铃，就数不清天。』他在零下的夜里把饼靠火化冰珠，说观梅与观雪是同一门功课——都看落。",
    storyEn: "Mingyuan was no ordinary monk. He spent five years in the Imperial Academy at Lin'an as a young man: could recite the entire Zuo Commentary from memory, could solve cubic equations with counting rods. In the autumn of his thirtieth year, he stood by the West Lake and watched a plum tree drop all its blossoms at once — in September, four months before the proper season. He asked every flower farmer and every Taoist priest in Lin'an; no one could explain it. He worked through the night with his counting rods and arrived at a hexagram — Xian, Influence. It was not the flower that had broken. The earth's breath had drawn the sky's hour forward. From that day he never returned to the Academy. He put on a monk's robe patched seven times and walked west — not to find a lost scripture, but to follow the question he had not been able to answer. Now he lives at the Pamir snowline, year after year, having taught himself to bake flatbread, to stitch sheepskin robes, and to keep a water-skin from freezing solid at thirty below. These crafts, he says, are more solid than any scripture. Scriptures are written on paper. What his hands learn each day is written on his bones. In the shelter he accepts only 'half a cake' as thanks — more, he pushes back: 'Courtesy at the snowline cannot be weighed in gold.' Toward Franks he is curious more than wary: 'Your god is nailed to wood; our hinge falls with plum blossoms — perhaps one snowfall, two sets of footprints.' Firewood at the snowline shelter is counted stick by stick; before casting he counts camel-bells — 'If you cannot count the bells, you cannot count Heaven.' On nights below freezing he melts ice-beads from cake by the fire; watching plum fall and snow fall, he says, is one lesson — both are about falling.",
    trial: { kind: "meihuaCast", need: 1,
      taskZh: "以此刻之数起一卦", taskEn: "Cast a hexagram from the numbers of this moment" },
    gradZh: "僧人把饼掰一半给你：「卦不难起，难在起卦时心里那个问题干不干净。」",
    gradEn: "He breaks the cake and gives you half. 'Casting is easy. What is hard is having a clean question when you cast.'"
  },
  {
    method: "iching", at: "shangdu", ic: "☯",
    zh: "太史院 耶律先生", en: "Master Yelü of the Astronomical Bureau",
    civZh: "上都 · 太史院值房", civEn: "Shangdu · the Bureau's duty room",
    introZh: "太史院的值房里堆满了历书、星图和各地驿站送来的气象记录——库房里甚至有一卷从吐蕃带回来的雪线标高图，薄得透光，用细笔描着十二种不同的雪花形状。耶律先生坐在这一堆纸山后面，瘦得像一片夹在书页里的枯叶。但那双眼睛是活的——像书缝里漏出来的两粒光。『大汗殿前不许妄言——我们不说吉凶，只说象。三枚铜钱从下往上掷六次——下面是已成的，上面是将来的。不是预测命运——是把已经发生但还没被看见的东西，摆到今天的光下面。学会了，你在这座宫里说话就有分量。学不会——嘘——不要紧，只要不学成半吊子。这座宫里不缺半吊子，缺的是一个法兰克人肯低下头来认认真真学六爻的起法。』",
    introEn: "The Bureau's duty room is heaped with almanacs, star-charts, and weather records from every post-station in the realm — there is even a snowline elevation map brought back from Tibet, tissue-thin, drawn with twelve distinct patterns of snowflake in a fine brush. Master Yelü sits behind this mountain of paper, thin as a dead leaf pressed between pages. But his eyes are alive — two points of light leaking from between the bindings. 'Before the Khan we do not say lucky or ill. We say only what the image shows. Three copper coins, cast six times from the bottom upward. Below is what has become; above, what is coming. It is not about foretelling fate. It is about taking something that has already happened but has not yet been seen, and holding it under today's light. Learn it, and your words carry weight in this palace. Fail to learn it — hush — that's all right, as long as you don't learn it half. This court has plenty of half-learned men. What it does not yet have is a Frank willing to bow his head and learn, properly, how six lines are cast.'",
    storyZh: "耶律先生——全名耶律履——不是汉人。他是契丹人，辽朝皇族的远裔。他的曾祖父曾在金朝的翰林院里掌管历法，蒙古大军破中都时，曾祖父抱着浑天仪的核心铜环跳了井。铜环被捞上来了，人没有。耶律家从此不再造浑天仪，只做一件事——算。耶律先生可以在没有星盘的情况下，凭记忆推算出木星在未来二十年内每一次冲日的位置，误差不超过半个度。大汗忽必烈在殿前第一次听他报星象时，从宝座上站起来，走了三步，又走回来，说了两个字：『留用。』他留了十五年，如今是太史院最老的值房官——老到没有人敢说他到底多大年纪。上都夏宫金顶刺眼，他却只穿一袭洗旧的青袍，腰间挂太史院铜印；三枚铜钱磨得发亮，是他唯一收过学徒的「束脩」——「钱够掷六爻即可，多了反脏了卦。」他最怕不是算错一个日食的时辰——是死后这一屋的纸没人再翻，被新来的官员当柴烧掉。『纸不怕火——纸怕的是没有人再在乎它上面写了什么。』对法兰克人他只叮嘱一句：「殿前不说吉凶，只说象。学会闭嘴，你才有资格开口。」值房窗外金顶反光刺目，他用历书遮额，铜钱在掌心温着——『凉钱出躁卦，温了再掷。』",
    storyEn: "Master Yelü — his full name is Yelü Lü — is not Chinese. He is a Khitan, a distant scion of the Liao imperial line. His great-grandfather kept the calendar at the Jin court; when the Mongol army broke the Central Capital, his great-grandfather threw himself into a well clutching the brass core-ring of the armillary sphere. The ring was retrieved. The man was not. The Yelü family have never built another armillary. They do only one thing now: calculate. Master Yelü can, without an astrolabe, compute from memory the position of Jupiter at every opposition for the next twenty years, accurate to within half a degree. The first time he reported planetary positions before Kublai Khan in the great hall, the Khan rose from his throne, walked three paces, walked back, and spoke two words: 'Keep him.' He has been kept for fifteen years now and is the oldest duty-room officer in the Bureau — so old that no one dares ask his age. Shangdu's summer roofs blaze gold; he wears only a washed-out blue robe and the Bureau's copper seal at his waist. Three copper coins worn bright are the only 'tuition' he has ever taken from a student — 'Enough to cast six lines; more soils the hexagram.' His greatest fear is not of miscomputing an eclipse. It is that after he dies, no one will turn the pages in this room, and the new officials will burn them for kindling. 'Paper fears no flame,' he says. 'Paper fears only that no one will care what is written on it.' To Franks he gives one caution: 'Before the throne we do not say lucky or ill — only image. Learn silence first; then you may speak.' Gold roofs glare outside the duty room; he shades his brow with an almanac and warms the coins in his palm — 'Cold coins cast restless lines; warm them first.'",
    trial: { kind: "ichingCast", need: 3,
      taskZh: "掷六爻成卦，得阳爻三数以上", taskEn: "Cast six lines; three or more must come up yang" },
    gradZh: "耶律先生在你的行囊上盖了太史院的印：「有此印，沿途官驿不敢拦你。」",
    gradEn: "He stamps the Bureau's seal on your pack. 'With this, no post station on the road will turn you away.'"
  },
  {
    method: "dream", at: "khanbaliq", ic: "🌙",
    zh: "圆梦人 撒里蛮", en: "Sarïman, Reader of Dreams",
    civZh: "大都 · 宫墙外的圆梦摊", civEn: "Khanbaliq · a dream-stall outside the palace wall",
    introZh: "宫墙外摆着一张矮桌，桌子上只有一支秃笔、一叠纸、一个破了口的粗瓷茶碗。撒里蛮长得既不像汉人也不像蒙古人——他是畏兀儿人，用的是回鹘字母，却能说五种语言。他摊上永远没有招牌，因为不需要——每天都有一大清早从宫墙侧门溜出来的宫女和内侍在他桌前排队，手里捏着昨夜记下来的梦——有的写在绸子上，有的画成歪歪扭扭的图。『大汗昨夜梦见了白马——满朝没人敢解。我解了。因为我懂一件事：梦不是预言，梦是你自己没说出口的话。你把它说出来，它就不吓人了。马是白的——说明不是死，是空。空不是坏事——只有空着，才能装新东西。』",
    introEn: "A low table outside the palace wall holds a worn-out brush, a stack of paper, and a chipped ceramic tea-bowl. Sarïman looks neither Chinese nor Mongol — he is a Uighur, writes in the Uighur script, and can speak five tongues. His stall never has a sign. It doesn't need one — every morning palace maids and eunuchs slip out through the side gate and line up at his table clutching dreams written down during the night, some on silk, some drawn as wobbly pictures. 'The Khan dreamt of a white horse last night — the whole court was afraid to read it. I did. Because I know one thing: a dream is not prophecy. It is the sentence you did not say aloud. Say it, and it stops being frightening. A white horse — not death, but emptiness. And emptiness is no ill — only an empty space can hold something new.'",
    storyZh: "撒里蛮的本业不是占梦——他最早是在高昌回鹘的佛寺里抄经的。十三岁能写回鹘、汉、梵三种文字的佛典，手指上有被经线反复勒出的老茧。二十岁那年，寺院被兵火毁了，他随逃难的人群一路向东，到了大都，在宫墙外摆了张桌子打算替人代写书信——却发现每个来写信的人，先要讲一个梦。有时候梦比信更急——梦见孩子病了、梦见水淹了庄稼、梦见死去多年的母亲在门外站着不说话。撒里蛮渐渐发现他不用抄经也能帮人——他只要听完一个梦，然后问一句『你觉得这件事像什么』。那个「像什么」总能解开写信时堵住的那口气。他现在的价钱是：一个梦换一碗茶——或者三文铜钱。如果有官宦子弟梦见科举题目，价格另议。他穿一件半新的畏兀儿长袍，腰间挂秃笔与墨盒；桌上一只破口粗瓷碗，是他收茶钱的量器——「茶满则梦尽，不必多问。」宫墙的鼓声按时辰响起，他说那秩序感很像威尼斯的钟楼——「只是你们用铜，我们用皮。」对法兰克人他格外耐心：「你们的周公叫灵魂；我们的周公叫影子。影子跟着人走，梦跟着影子走。」有时宫女只递一张空白纸，他便在碗沿写回鹘字母，说『空纸也是梦——梦到不敢写的那一行。』",
    storyEn: "Sarïman was not always a dream-reader. He began as a scribe in a Uighur Buddhist monastery in Qocho, copying sutras. By thirteen he could write Buddhist texts in Uighur, Chinese, and Sanskrit, his fingers callused from the binding-thread. At twenty the monastery burned in a war, and he walked east with the refugees until he came to Khanbaliq, where he set up a table outside the palace wall meaning to earn his keep writing letters — only to discover that every person who came to dictate a letter first had to tell a dream. Sometimes the dream was more urgent than the letter: a child taken sick, water flooding the fields, a mother dead many years standing at the door and saying nothing. Sarïman discovered he didn't need scripture to help — he only had to listen to a dream, then ask, 'What does it remind you of?' That 'it reminds me of' was always the key that unlocked the breath stuck in the letter-writer's chest. His price now: one dream for one bowl of tea — or three copper coins. If the dreamer is an examination candidate who dreamt of the exam topic, the price is negotiable. He wears a half-new Uighur robe, brush and ink-box at his belt; a chipped bowl on the table measures his tea-fee — 'When the bowl is full, the dream is done; ask no more.' The palace drums divide the hours; he says the order feels like Venice's campanile — 'Only you use bronze; we use hide.' With Franks he is especially patient: 'Your Duke of Zhou is called soul; ours is called shadow. Shadow follows the man; the dream follows the shadow.' Sometimes a maid brings blank paper; he writes Uighur letters on the bowl-rim — 'Blank paper is also a dream — the line you dared not write.'",
    trial: { kind: "dreamTell", need: 1,
      taskZh: "说出一个梦，认出其中的梦象", taskEn: "Tell a dream; find the symbol in it" },
    gradZh: "「周公与你们西边的人说的其实是一回事，」撒里蛮笑了，「只是他们管那个叫『灵魂』。」",
    gradEn: "'The Duke of Zhou and your westerners are saying the same thing,' he smiles, 'only they call it the soul.'"
  },
  {
    method: "bazi", at: "hangzhou", ic: "🏮",
    zh: "命馆先生 沈五", en: "Shen the Fifth, of the Fate Shop",
    civZh: "行在 · 御街命馆", civEn: "Kinsay · a fate shop on the Imperial Way",
    introZh: "行在的御街上，一家门面窄得像一道缝的命馆，招牌上只有四个字——「沈五排盘」。店堂小得只能放下两张椅子，但墙上挂着一幅用蝇头小楷抄的《渊海子平》——那是沈五的父亲沈三花了七年抄成的，用墨之黑如同打了蜡的炭，每一笔画都像是用尺子比着的——但其实是全凭手。『年月日时，四柱八字。』沈五翻开一本旧得只剩半截封面的通书：『这不是算你哪天发财——是看你这个人是什么材料。木要土养，金要水磨。知道自己是什么材料，才知道该往哪儿使劲。』他看了你的生辰一眼，用一支磨秃了尖的笔在纸上画了几笔，停住了。『你这八字——我没有见过这样的组合。但我能告诉你一件事：你的日主是火，你的人生的燃料不是你自己的东西。火要烧，就得找别人的薪。你在路上找的那些师傅——你自己也说不清为什么要学那么多东西——不是因为你贪心，是你的八字要这些。』",
    introEn: "On the Imperial Way in Kinsay, a shop so narrow it looks like a crack in the wall, bearing only four characters on its sign: 'Shen the Fifth — Charts Cast.' The room barely holds two chairs, but on the wall hangs a hand-copied Complete Principles of the Eight Characters in script so fine you could slip it under a needle — Shen's father, Shen the Third, spent seven years on it, and the ink is black as waxed charcoal, every stroke straight as though drawn with a ruler, though none were. 'Year, month, day, hour — four pillars, eight characters.' He opens an almanac whose cover has been worn away to half its spine: 'This won't say when you'll get rich. It says what stuff you're made of. Wood wants earth; metal wants water. Know your material and you'll know where to spend yourself.' He glances at your birth hour, draws a few marks with a worn-down brush point, and stops. 'This chart of yours — I have never seen such a combination. But I can tell you one thing. Your Day Master is Fire. Fire does not burn on its own fuel. It must find another's dry timber. All those masters you collect on the road — you yourself cannot explain why you need so many arts — it is not greed. It is your Eight Characters asking for them.'",
    storyZh: "沈五的父亲沈三七岁开始学排盘，学了三十年，排了一万六百张盘。他自己的八字是水命——水要金生，金要土藏，土从来不够，所以他穷了一辈子。他死前给沈五留了两件东西：那幅手抄的《渊海子平》，和一句话——「收钱可以收三文以上，但永远不要收超过一个船工一天的工钱。」沈五照着做已经二十二年，他排过的盘已经超过了他父亲。他排盘不收生辰——生辰太容易伪造——他要问三个问题：你娘生你的时候是顺产还是难产，你第一次离家是雨季还是旱季，你最近一次哭是为了什么事。这三个问题的答案，他说比时辰更可靠。「宫殿和时辰都是人定的——但你是怎么来的、你怎么走的、你为什么哭——这些是天定的。」他有一个盒子，装满了这些问答纸条，每一条他都能说出是谁——不是姓名，是八字。他现在四十三岁，右眼已经看不太清纸上的字了，但他说没关系——「八字是算的，不是看的。」行在御街上茶一文、签三文；他的命馆窄得像缝，墙上蝇头小楷《渊海子平》像打了蜡的炭。对法兰克人他只摇头笑：「你们问哪天发财——我只问你是什么材料。材料不对，再好的日子也烧不着。」御街雨湿青石，他仍坐缝里的店堂，右眼贴纸看字，左眼听客人说话——『听比看准。』",
    storyEn: "Shen the Fifth's father, Shen the Third, began studying chart-casting at age seven and studied for thirty years, casting ten thousand six hundred charts. His own Eight Characters were Water — Water needs Metal to generate it, Metal needs Earth to store it, and Earth was never enough — so he was poor all his life. Before he died, he left Shen the Fifth two things: that hand-copied Principles of the Eight Characters, and a sentence — 'You may charge more than three coppers, but never more than a boatman earns in a single day.' Shen the Fifth has followed that rule for twenty-two years and has now cast more charts than his father ever did. He does not ask for the birth hour — that is too easy to falsify. He asks three questions: was your mother's labor smooth or hard, did you first leave home in the wet season or the dry, and what was the last thing that made you weep. The answers to these three, he says, are more reliable than any clock. 'Palaces and time-standards are invented by men. But how you arrived in this world, how you departed the gate, and why you wept — those are written by heaven.' He keeps a box of those question slips; he can identify each one — not by name, but by the Eight Characters inscribed above the answers. He is forty-three now and his right eye can barely read the paper. It doesn't matter, he says. 'The Eight Characters are calculated, not read.' On Kinsay's Imperial Way tea is one cash, lots three; his shop is a crack in the wall, the fine-script Principles on the wall black as waxed charcoal. To Franks he only shakes his head and smiles: 'You ask which day you'll get rich — I only ask what stuff you're made of. Wrong material, and even a fair day will not catch.' When rain wets the Imperial Way's blue stones he still sits in the crack-shop, right eye to the paper, left ear to the guest — 'Hearing beats seeing.'",
    trial: { kind: "baziCast", need: 1,
      taskZh: "排一张四柱盘，认出日主", taskEn: "Cast the four pillars and find the Day Master" },
    gradZh: "沈五收了你三文钱：「明码标价，童叟无欺。占者收钱不丢人，收了钱还骗人才丢人。」",
    gradEn: "He takes three coppers. 'Posted prices, no haggling. There is no shame in a diviner taking money — only in taking it and lying.'"
  },
  {
    method: "jiaobei", at: "quanzhou", ic: "🌗",
    zh: "天妃宫庙祝 陈婆", en: "Granny Chen, Keeper of the Tianfei Shrine",
    civZh: "泉州 · 天妃宫", civEn: "Quanzhou · the Tianfei temple",
    introZh: "天妃宫的香火永远不断——不是因为来的人多，是因为陈婆每年正月十六亲自补上新火，用的是一根从莆田湄洲祖庙请回来的香。她说婆祖娘娘生前也是这样，点燃一支香的功夫能听三位渔妇诉苦，又在下一支香燃完之前替四条船看了风信。她的福建话混着南洋的马来词——她年轻时跟着船跑过占城、暹罗、爪哇，在每一个港口的天妃庙里都供过三天香，回来手上多了一本记了十六种语言的祷告集——法郎机语的「海上平安」、波斯语的「风调顺我心」、暹罗语的「海神看见我」。她最得意的不是这些，是她教会了一个不识字的阿拉伯商人怎么掷筊——『语言不通不要紧——筊杯落到地上，是正是反，谁看都一样。』",
    introEn: "The incense at Tianfei temple is never allowed to go out — not because so many people come, but because Granny Chen personally renews the flame every sixteenth day of the first lunar month, using an ember carried all the way from the matriarch temple on Meizhou Island. The goddess, she says, was the same way when she lived among mortals — she could hear three fishermen's wives weep in the time it took one incense stick to burn, and still read the wind for four ships before the second stick was done. Granny Chen's Fujian dialect is salted with Malay from the South Seas — she followed boats to Champa, Siam, and Java as a young woman, burning three-day offerings at every Tianfei shrine in every port, and came home with a book of prayers in sixteen languages: 'Safe passage' in Frankish, 'Wind, follow my heart' in Persian, 'The sea-god sees me' in Siamese. What she is proudest of is none of these. She taught an illiterate Arab trader how to cast the moon blocks — 'No shared language is needed. When the blocks hit the ground — one up, one down — everyone sees the same thing.'",
    storyZh: "陈婆七岁时被她父亲送进了天妃宫——不是因为家里养不起，是因为她出生的那个夜里，她父亲的渔船在台湾海峡遇上了一场本不该有的风暴，母亲在岸上跪了三个时辰，发了三个誓，最后一个是「若母女平安，此女成年归天后」。母亲活下来了，她也活下来了，所以她从七岁起就在天妃宫里点灯洒扫。她嫁过一回人——二十三岁那年嫁了一个从占城来刺桐做香料生意的华商子弟，在占城住了九年。后来丈夫死在爪哇的一场海难里，她一个人回刺桐，从此穿青衣，不再嫁。有人说她这一生最大的苦不是守寡——是她站在天妃宫里替别人掷筊的时候，自己心里也经常想问一句话，但她从来不问。『我替天妃管着这两片木头——问天妃的事不该由我开口。她要是想告诉我什么，她会自己把筊杯落地——反正我每天都要扫这块地，不是正面就是反面，总会看见的。』掷筊本身不收费，香油钱随意——穷船户三炷，富商一箱胡椒钱也收。刺桐胡椒之盛，马可说可比亚历山大百倍；陈婆只说：「货再多，风一变，全是纸。先问神，再开舱。」香灰扫进陶罐，从不踩踏；她说筊杯落地的声音，比胡椒落舱更像真话。她每年正月十六用湄洲祖庙的香续火；香油钱随意，穷三炷，富一箱，从不催。",
    storyEn: "Granny Chen was sent to the Tianfei temple at the age of seven — not because her family could not afford to keep her, but because on the night she was born, her father's fishing boat was caught in a storm in the Taiwan Strait that should not have risen. Her mother knelt on the shore for the space of three double-hours and made three vows. The last was: 'If the mother lives and the child lives, this daughter will return to the Goddess when she is grown.' Her mother lived. So did she. From seven years old she has lit incense and swept the temple stones. She married once — at twenty-three, into a Chinese merchant family from Champa that traded spices into Zayton, and spent nine years in Champa. Then her husband died in a shipwreck off Java. She returned to Zayton alone, put on blue robes, and has not remarried. Some say the hardest part of her life was not widowhood. It is that she casts the moon blocks for others every day, and there is often a question she herself would like to ask — but she never does. 'I keep these two pieces of wood for the Goddess. The questions to the Goddess are not mine to speak. If she wants to tell me something, she'll make the blocks fall herself. I sweep this floor every day. One way or the other — I will see it.' Casting costs nothing; incense money is freewill — three sticks from a poor crew, a pepper-chest's worth from a rich merchant. Zayton's pepper, Marco said, outdoes Alexandria a hundredfold; Granny Chen only says: 'Cargo without end is still paper when the wind turns. Ask the goddess first; open the hold second.' Ash goes into a clay jar, never underfoot; the sound of blocks hitting stone, she says, is truer than pepper hitting the hold. Each sixteenth of the first month she renews the flame with Meizhou incense; incense money is freewill — three sticks or a chest — she never presses.",
    trial: { kind: "jiaobeiCast", need: 1,
      taskZh: "掷出一次圣筊（三掷之内）", taskEn: "Cast Sheng-jiao within three throws" },
    gradZh: "陈婆点了三炷香：「记住，问神是为了定自己的心。心定了，神就答了。」",
    gradEn: "She lights three sticks of incense. 'You ask the goddess to settle your own heart. Once it settles, she has answered.'"
  }
];

FQ.mentorFor = m => FQ.MENTORS.find(x => x.method === m);
FQ.mentorsAt = nodeId => FQ.MENTORS.filter(x => x.at === nodeId);

/* Gates that need no schooling — anyone may toss a coin or draw a temple lot */
FQ.FREE_GATES = ["coinYang", "lot", "dreamChoice", "case", "tarotAny"];
/* which learned art a gate type demands */
FQ.GATE_METHOD = {
  tarotAny: "tarot", tarotLow: "tarot",
  diceFire: "astrodice", diceElem: "astrodice", diceHouse: "astrodice",
  meihua: "meihua", ichingYang: "iching", jiaobei: "jiaobei"
};
